'use client';
import { useState } from 'react';
import { ArrowUpRight, Check, Copy } from 'lucide-react';
import evidence from './evidence.json';
import { Button } from '@/components/ui/button';
const repo='https://github.com/Kevin-Zhouu/jevify';
const example=repo+'/blob/c3cdda6/eval/results/dev-03/vercel_enum-codex-headless/original/';
const command='npx skills add Kevin-Zhouu/jevify';
export default function Home(){
 const [notice,setNotice]=useState('');
 async function copy(){try{await navigator.clipboard.writeText(command);setNotice('Copied to clipboard.')}catch{setNotice('Select and copy the command above.')}}
 return <div className="shell"><a href="#main" className="skip">Skip to content</a>
 <header><a href="#" className="brand">jevify<span>_</span></a><nav aria-label="Main navigation"><a href="#install">Install</a><a href={repo+'/blob/main/skills/jevify/INSTALL.md'}>Docs</a><a href={repo}>GitHub <ArrowUpRight size={14}/></a></nav></header>
 <main id="main"><section className="intro"><div className="project-line"><span>Kevin-Zhouu / jevify</span><span>Agent skill</span></div><img className="logo" src="/media/jevify-logo.png" alt="jevify" width="300" height="100"/><h1>Get your agents running<br className="wide"/> on Jev today</h1><a className="session-preview" href="/media/jevify-session.gif" aria-label="Open the real Jevify session recording"><img src="/media/jevify-session.gif" alt="Real Jevify session in Codex: setup questions, audit plan, approval, and code diff" width="1040" height="448"/></a><p className="session-caption">Real Codex session · scripted user replies · waits trimmed · no-key conversion. <a href={repo+'/tree/landing/evidence-first/docs/demos/jevify-session'}>Recording & output ↗</a></p><p>Jevify audits your repo and moves suitable decision calls to Jev.<br/>You approve the changes. Your original LLM stays as fallback.</p><div className="harnesses">Codex · Claude Code (beta) <span>/</span> <a href="#status">Evaluation status ↓</a></div>
 <div id="install" className="install"><div className="command"><span className="dollar">$</span><code>{command}</code><Button variant="ghost" onClick={copy} aria-label="Copy installation command" className="copy">{notice==='Copied to clipboard.'?<Check size={17}/>:<Copy size={17}/>}</Button></div><p className="install-note" role="status">{notice||'Run in your project. Choose your coding agent in the installer.'}</p></div></section>
 <section id="changes" className="section"><div className="section-head"><h2>What Jevify changes</h2><a href={example+'JEV_CONVERSION_REPORT.md'}>Conversion report <ArrowUpRight size={14}/></a></div><p className="section-sub">Your existing LLM call becomes the fallback. Jev handles confident decisions.</p><p className="note evidence-caption">Actual Codex output from the recorded DEV03 movie-genre conversion. Original call and return fields are preserved.</p><pre className="code-evidence" aria-label="Recorded Jevify conversion diff"><code>{evidence.workflowDiff}</code></pre><div className="ref-links"><a href="/evidence/vercel-enum.diff">Call-site diff ↓</a><a href={example+'workflow.ts'}>Converted workflow ↗</a><a href={example+'jevDecisions.ts'}>Decisions module ↗</a></div><details className="policy-details"><summary>See the Jev question, confidence gate, and fallback</summary><p className="note">Exact excerpts from the same decisions module; intervening transport and error-handling code omitted. The full module is linked above.</p><pre className="code-evidence"><code>{evidence.policy}</code></pre><pre className="code-evidence"><code>{evidence.gate}</code></pre><pre className="code-evidence"><code>{evidence.fallback}</code></pre></details><p className="note">32 live pairs: 29 accepted at the 0.90 threshold, 29/29 agreed with the original, and 3 fell back. Estimated cascade cost was 4.9% higher on these samples. A small check set, not a general guarantee. <a href={example+'JEV_PARITY.json'}>Raw results ↗</a></p></section>
 <section id="demo" className="section"><div className="section-head"><h2>LLM vs Jev for decisions</h2><a href={repo+'/tree/main/docs/demos'}>Raw data <ArrowUpRight size={14}/></a></div><p className="section-sub">12 questions → 136 lines of JSON.</p><video controls playsInline preload="metadata" poster="/media/json-race.png" aria-label="LLM vs Jev for decisions: captured JSON response timings"><source src="/media/claude-vs-jev.mp4" type="video/mp4"/><a href="/media/claude-vs-jev.mp4">Download comparison</a></video><div className="measurement"><span>Jev <strong>0.44s</strong></span><span>Claude Haiku 4.5 <strong>5.11s</strong></span><span>Category agreement <strong>12/12</strong></span></div><p className="note">A single synthetic example via OpenRouter, replayed at actual speed. Probability and confidence values differ. Not a general benchmark.</p></section>
 <section id="usage" className="section"><div className="section-head"><h2>How it works</h2><span className="meta">No key needed to audit</span></div><div className="prompt"><span>Claude Code</span><p>/jevify convert this workflow</p></div><p className="note">In Codex: <code>$jevify convert this workflow</code>. Name a file, folder, or agent. Jevify handles setup and the approval step.</p><dl className="flow"><div><dt>01 / Audit</dt><dd>Find decision calls and flag unsuitable ones.</dd></div><div><dt>02 / Approve</dt><dd>Choose what changes, and where: branch, clone, or report.</dd></div><div><dt>03 / Convert</dt><dd>Keep interfaces intact and add the approved fallback.</dd></div><div><dt>04 / Validate</dt><dd>Run tests. Compare real answers, latency, and cost with a key.</dd></div></dl><p className="note">Just exploring? /jevify audit this repo</p></section>
 <section id="minecraft" className="section"><div className="section-head"><h2>Built with Jev</h2><a href="https://github.com/rmalde/minecraft-agent">Source code <ArrowUpRight size={14}/></a></div><p className="section-sub">Minecraft: taking down the Ender Dragon.</p><a className="community-link" href="https://x.com/rronak_/status/2101544156757950697"><span>Minecraft × Jev + Astra</span><strong>Watch the Ender Dragon demo <ArrowUpRight size={20}/></strong><span>Original video by Ronak Malde ↗</span></a><p className="note">Community showcase, not a Jevify conversion. Pre-surveyed seed, Peaceful mode.</p></section>
 <section className="section reference"><h2>Bring your key</h2><p>Use TYPESAFE_API_KEY or OPENROUTER_API_KEY through your environment or the hidden-input launcher. Keep your original provider key for fallback. No Jev key is needed for an audit; live validation requires one.</p><div className="ref-links"><a href={repo+'/blob/main/skills/jevify/INSTALL.md'}>Install manually <ArrowUpRight size={14}/></a><a href={repo+'/blob/main/skills/jevify/references/credentials.md'}>Add your API key <ArrowUpRight size={14}/></a><a href={repo+'/blob/main/skills/jevify/references/configuration.md'}>Run headlessly <ArrowUpRight size={14}/></a></div></section>
 <aside id="status" className="status"><span className="status-label">Development status</span><p>Codex: 12/12 DEV runs passed in each of the last two rounds. Claude Code is beta: conversion validation failures remain. Held-out testing is pending; equal reliability across both agents is not yet proven.</p><a href={repo+'/blob/main/REPORT.md'}>Full report <ArrowUpRight size={14}/></a></aside>
 </main><footer><span>An independent skill for TypeSafe’s Jev.</span><a href="https://docs.typesafe.ai/">TypeSafe docs <ArrowUpRight size={14}/></a><a href="/media/jevify-logo.png" download="jevify-logo.png">Logo ↓</a></footer></div>
}
