'use client';
import { useState } from 'react';
import { ArrowUpRight, Check, Copy } from 'lucide-react';
import { Button } from '@/components/ui/button';
const repo='https://github.com/Kevin-Zhouu/jevify';
const command='npx skills add Kevin-Zhouu/jevify';
export default function Home(){
 const [notice,setNotice]=useState('');
 async function copy(){try{await navigator.clipboard.writeText(command);setNotice('Copied to clipboard.')}catch{setNotice('Select and copy the command above.')}}
 return <div className="shell"><a href="#main" className="skip">Skip to content</a>
 <header><a href="#" className="brand">jevify<span>_</span></a><nav aria-label="Main navigation"><a href="#install">Install</a><a href={repo+'/blob/main/skills/jevify/INSTALL.md'}>Docs</a><a href={repo}>GitHub <ArrowUpRight size={14}/></a></nav></header>
 <main id="main"><section className="intro"><div className="project-line"><span>Kevin-Zhouu / jevify</span><span>Agent skill</span></div><img className="logo" src="/media/jevify-logo.png" alt="jevify" width="300" height="100"/><h1>Turn your existing AI workflows<br className="wide"/> into Jev-powered workflows.</h1><p>Find suitable LLM calls. Convert with your approval.<br/>Keep your original model as a fallback.</p><div className="harnesses">For Codex & Claude Code <span>/</span> <a href="#status">Evaluation status ↓</a></div>
 <div id="install" className="install"><div className="command"><span className="dollar">$</span><code>{command}</code><Button variant="ghost" onClick={copy} aria-label="Copy installation command" className="copy">{notice==='Copied to clipboard.'?<Check size={17}/>:<Copy size={17}/>}</Button></div><p className="install-note" role="status">{notice||'Run in your project. Choose your coding agent in the installer.'}</p></div></section>
 <section id="demo" className="section"><div className="section-head"><h2>See it run</h2><a href={repo+'/tree/main/docs/demos'}>Raw data <ArrowUpRight size={14}/></a></div><p className="section-sub">12 questions → 136 lines of JSON.</p><video controls playsInline preload="metadata" poster="/media/json-race.png" aria-label="Claude vs Jev: captured JSON response timings"><source src="/media/claude-vs-jev.mp4" type="video/mp4"/><a href="/media/claude-vs-jev.mp4">Download comparison</a></video><div className="measurement"><span>Jev <strong>0.44s</strong></span><span>Claude Haiku 4.5 <strong>5.11s</strong></span><span>Category agreement <strong>12/12</strong></span></div><p className="note">A single synthetic example via OpenRouter, replayed at actual speed. Probability and confidence values differ. Not a general benchmark.</p></section>
 <section id="usage" className="section"><div className="section-head"><h2>Use it in your repo</h2><span className="meta">No key needed to audit</span></div><div className="prompt"><span>You</span><p>Use jevify to convert this workflow to Jev.<br/>Show me the plan first.</p></div><dl className="flow"><div><dt>01 / Audit</dt><dd>Find decision calls and flag unsuitable ones.</dd></div><div><dt>02 / Approve</dt><dd>Choose what changes, and where: branch, clone, or report.</dd></div><div><dt>03 / Convert</dt><dd>Keep interfaces intact and add the approved fallback.</dd></div><div><dt>04 / Validate</dt><dd>Run tests. Compare real answers, latency, and cost with a key.</dd></div></dl><p className="note">Just exploring? Ask for a report-only audit.</p></section>
 <section className="section reference"><h2>Where Jev fits</h2><p>Routing, classification, rubric scoring, and bounded yes/no decisions. Generation stays with your LLM.</p><div className="ref-links"><a href={repo+'/blob/main/skills/jevify/INSTALL.md'}>Install manually <ArrowUpRight size={14}/></a><a href={repo+'/blob/main/skills/jevify/references/credentials.md'}>Add your API key <ArrowUpRight size={14}/></a><a href={repo+'/blob/main/skills/jevify/references/configuration.md'}>Run headlessly <ArrowUpRight size={14}/></a></div></section>
 <aside id="status" className="status"><span className="status-label">Development status</span><p>Codex: 12/12 DEV runs passed in each of the last two rounds. Claude Code: validation failures remain. Held-out testing is pending.</p><a href={repo+'/blob/main/REPORT.md'}>Full report <ArrowUpRight size={14}/></a></aside>
 </main><footer><span>An independent skill for TypeSafe’s Jev.</span><a href="https://docs.typesafe.ai/">TypeSafe docs <ArrowUpRight size={14}/></a><a href="/media/jevify-logo.png" download="jevify-logo.png">Logo ↓</a></footer></div>
}
